train:
  num_workers: 8
  batch_size: 4
  shuffle: true
  pin_memory: true
  persistent_workers: true
  pack_sequences: false
  prepacked_sequences: false
  max_length: 1024
validation:
  num_workers: 0
  batch_size: 4
  shuffle: false
  pin_memory: true
  persistent_workers: false
  pack_sequences: false
  prepacked_sequences: false
  max_length: 1024
